### ISSUE TITLE
Announcement data too long

### ISSUE THREAD

**Issue by jpuigs** [Opendigitalradio/dablin#63] opened 2020-05-06 13:17 UTC
On DABItalia mux, the announcement that appears is so long that makes app expand to almost all screen.....
I've tried modifying code ,  `frame_label_asu.set_hexpand(false);`  but it does same....

![imatge](https://user-images.githubusercontent.com/44906458/81181851-50723e80-8fad-11ea-8084-dfe08cbd8e1b.png)

It expands to...........

![imatge](https://user-images.githubusercontent.com/44906458/81181321-967ad280-8fac-11ea-9b13-eb3ea1778e46.png)

I don't know how it could be fixed.... to be split into several lines...

**Comment by andimik** [comment] 2020-05-06 14:58
Let's say, what DAB Italia is doing has no sense. I will report it to them.

**Comment by jpuigs** [comment] 2020-05-06 15:00
They have enabled the 11 types of announcements.....
Besides, if you look at the time clock, seconds appear and dissapear continuosly....

**Comment by basicmaster** [comment] 2020-05-10 12:45
> On DABItalia mux, the announcement that appears is so long that makes app expand to almost all screen.....

> They have enabled the 11 types of announcements.....

This (all eleven defined types supported) seems to be a default announcement setting, which is of course a bad habit. DABlin now regularly inserts line breaks to address this, in 7bece7e00bb9a05d8e0a012b082b584e4098dbcb.

>  I've tried modifying code , `frame_label_asu.set_hexpand(false);` but it does same....

Correct, because this only means that the field size may change as soon as the window size is changed. However, if the text is already long enough, the text field has to be long enough, too, in order to contain the complete text.

>  Besides, if you look at the time clock, seconds appear and dissapear continuosly....

This is indeed allowed; I will address this later today.

**Comment by jpuigs** [comment] 2020-05-10 15:29
> > Besides, if you look at the time clock, seconds appear and dissapear continuosly....
> 
> This is indeed allowed; I will address this later today.

Yes, it seems that they already fixed it. Now seconds appear constantly....

One improvement for Announcements.
If you are listening f.i. Bayern 2 Nord, the announcement says: Road Traffic flash, and if you stop mouse over it, you can read: Cluster(s): 0x02 (SubChId 4).
I understand that this SubChId 4 is the programme where it'll appear the traffic info when available.
I think it'd be good to inform about the programme label too, (in this case it's BAYERN 1 Franken).
....And finally, the best of all would be that when transmitting live info (background changes colour), the programme name would appear too inside label:
Road Traffic flash (BAYERN 1 Franken) and a programme name has an hyperlink to zap to it directly...
:smile:

**Comment by andimik** [comment] 2020-05-10 17:02
DAB Italia's technician told me, they will keep this.

**Comment by basicmaster** [comment] 2020-05-10 21:17
> Yes, it seems that they already fixed it. Now seconds appear constantly....

The issue is now fixed in `next`.

This is (was?) probably a mode to also address older devices that are not aware of the long form for date/time. Actually I would assume that such devices don't support DAB+, so sending the short form is usually useless.

> One improvement for Announcements.
> If you are listening f.i. Bayern 2 Nord, the announcement says: Road Traffic flash, and if you stop mouse over it, you can read: Cluster(s): 0x02 (SubChId 4).
> I understand that this SubChId 4 is the programme where it will appear the traffic info when available.
> I think it would be good to inform about the programme label too, (in this case it's BAYERN 1 Franken).
> ....And finally, the best of all would be that when transmitting live info on other channel (background changes colour), the programme name would appear too inside label:
> Road Traffic flash (BAYERN 1 Franken) and a programme name had an hyperlink to zap to it directly...
> smile

Unfortunately I won't add such feature, for the simple reason that the subchannel has to be enough here. It is possible (and in use) that multiple services refer to the same subchannel and/or this references may change. This could lead to really long labels and would require to also consider this field when other data is updated. Therefore the feature is kept as simple as possible, for now at least.

**Closed** 2020-05-10 21:17 UTC

**Comment by jpuigs** [comment] 2020-05-10 21:51
:+1:
